package User;


public class DataIOException extends RuntimeException{ 

	public DataIOException(Throwable cause) {
		super(cause);
	}
	
}
